"use client";
import { useEffect, useState } from "react";
import { Check, Download, ExternalLink, Link2, Loader2, Package, Search, X } from "lucide-react";

type Category = { id: number; name: string };
type Item = { name: string; slug: string; description: string; images: string[]; regularPrice: number; sellPrice: number | null; categoryId?: number; stock?: number; freeDelivery?: boolean; isActive?: boolean };
export default function ProductImportClient() {
 const [value,setValue]=useState(""); const [items,setItems]=useState<Item[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [categoryId,setCategoryId]=useState(""); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [done,setDone]=useState<string[]>([]);
 useEffect(()=>{ fetch("/api/admin/product-import?mode=categories").then(r=>r.json()).then(x=>setCategories(x.categories||[])); },[]);
 const scan=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError("");setMessage("");try{const r=await fetch(`/api/admin/product-import?value=${encodeURIComponent(value)}`);const x=await r.json();if(!r.ok)throw new Error(x.error);setItems(x.items||[]);setCategories(x.categories||[]);setMessage(x.message||"");}catch(e){setError(e instanceof Error?e.message:"Could not scan");}finally{setLoading(false)}};
 const update=(i:number,key:keyof Item,val:unknown)=>setItems(a=>a.map((x,n)=>n===i?{...x,[key]:val}:x));
 const importSelected=async()=>{if(!categoryId)return setError("Select a Kmcmart category first");setSaving(true);setError("");const selected=items.map(x=>({...x,categoryId:Number(categoryId),stock:x.stock??50,isActive:true,freeDelivery:x.freeDelivery??false}));try{const r=await fetch("/api/admin/product-import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({items:selected})});const x=await r.json();setDone(x.results.filter((z:{ok:boolean})=>z.ok).map((z:{name:string})=>z.name));setMessage(`${x.results.filter((z:{ok:boolean})=>z.ok).length} product(s) imported successfully`);setItems([]);}catch(e){setError(e instanceof Error?e.message:"Import failed");}finally{setSaving(false)}};
 return <div className="space-y-5 pb-16"><div className="bg-white rounded-3xl border border-gray-100 shadow-sm p-5 md:p-7"><div className="flex items-start gap-3"><span className="grad-bg text-white rounded-2xl p-3"><Download size={20}/></span><div><h1 className="font-display text-xl md:text-2xl font-extrabold">Product Importer</h1><p className="text-xs font-semibold text-gray-400 mt-1">Import approved products from Kmc Bazar, review them first, then add them to Kmcmart.</p></div></div><form onSubmit={scan} className="mt-6 flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Link2 size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"/><input className="field !pl-11" value={value} onChange={e=>setValue(e.target.value)} placeholder="http://kmcbazar.com/product/product-slug or /category/accessories" required/></div><button disabled={loading} className="grad-bg text-white rounded-2xl px-6 py-3 text-sm font-extrabold flex items-center justify-center gap-2 disabled:opacity-60">{loading?<Loader2 className="animate-spin" size={16}/>:<Search size={16}/>} Scan Products</button></form><p className="mt-3 text-[11px] font-semibold text-gray-400">Use a single product URL or a category/shop URL. Only kmcbazar.com links are accepted.</p></div>
 {error&&<div className="bg-rose-50 border border-rose-100 text-rose-600 rounded-2xl p-4 text-sm font-bold">{error}</div>}{message&&<div className="bg-emerald-50 border border-emerald-100 text-emerald-700 rounded-2xl p-4 text-sm font-bold">{message}</div>}
 {items.length>0&&<div className="bg-white rounded-3xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-5 border-b border-gray-100 flex flex-col md:flex-row gap-3 md:items-center md:justify-between"><div><h2 className="font-display font-extrabold flex items-center gap-2"><Package size={18} className="text-[var(--g2)]"/> Review {items.length} product(s)</h2><p className="text-[11px] text-gray-400 font-semibold mt-1">Edit any field before importing.</p></div><div className="flex gap-2"><select className="field !pl-3 py-2.5 min-w-[190px]" value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Choose category…</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={importSelected} disabled={saving} className="grad-bg text-white rounded-xl px-4 py-2 text-xs font-extrabold flex items-center gap-2 disabled:opacity-60">{saving?<Loader2 size={14} className="animate-spin"/>:<Check size={14}/>} Approve & Import</button></div></div><div className="divide-y divide-gray-100">{items.map((x,i)=><div key={x.slug+i} className="p-4 md:p-5 grid grid-cols-[72px_1fr] md:grid-cols-[90px_1fr_150px] gap-4"><div className="w-[72px] h-[72px] rounded-2xl bg-gray-100 overflow-hidden">{x.images[0]&&<img src={x.images[0]} alt="" className="w-full h-full object-cover"/>}</div><div className="min-w-0 space-y-2"><input className="field !pl-3 py-2 font-bold" value={x.name} onChange={e=>update(i,"name",e.target.value)}/><div className="flex gap-2"><input type="number" className="field !pl-3 py-2" value={x.regularPrice} onChange={e=>update(i,"regularPrice",Number(e.target.value))}/><input type="number" className="field !pl-3 py-2" value={x.sellPrice??""} onChange={e=>update(i,"sellPrice",e.target.value===""?null:Number(e.target.value))} placeholder="Sale price"/></div><a href={`http://kmcbazar.com/product/${x.slug}`} target="_blank" className="text-[11px] font-bold text-[var(--g2)] inline-flex items-center gap-1">View source <ExternalLink size={11}/></a></div><button onClick={()=>setItems(a=>a.filter((_,n)=>n!==i))} className="text-gray-400 hover:text-rose-500 self-start justify-self-end" title="Remove"><X size={18}/></button></div>)}</div></div>}
 {done.length>0&&<div className="bg-white rounded-3xl border border-gray-100 p-5"><h2 className="font-extrabold text-emerald-600">Imported products</h2><ul className="mt-2 text-sm text-gray-600 list-disc pl-5">{done.map(x=><li key={x}>{x}</li>)}</ul></div>}
 </div>;
}
